ALTER TRIGGER AUDIT_CHADO_ACQPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ACQUISITION_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ACQ_REL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ANAFEAT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ANALYSISPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ANALYSIS_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ARRAYDESIGN_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ARRDESPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ASSAYPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ASSAY_PROJECT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ASSAY_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ASSMAT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_AUTHOR_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_BIOMATERIAL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_BIOMATPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_BIOMATREL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_BIOMATTRE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CHANNEL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CONTACT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CONTROL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CVREL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CVTERMPATH_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CVTERMSYNONYM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CVTERM_DBXREF_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CVTERM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_CV_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_DBXREFPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_DBXREF_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_DB_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_EIMAGE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ELEMENTRESULT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ELEMENT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ELEREL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ENVCVTERM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ENVIRONMENT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_EXPCVTERM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_EXPIMAGE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_EXPRESSION_PUB_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_EXPRESSION_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATCVPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATEXP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATGENO_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATPHENO_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATPROPPUB_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATRELAPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATREL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATSYN_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATURELOC_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATUREMAP_PUB_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATUREMAP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATUREPOS_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATUREPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATURERANGE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATURE_CVTERM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATURE_DBXREF_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_FEATURE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_GENOTYPE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_MAGDOC_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_MAGEML_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ORGANISMPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ORGANISM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_ORGDBX_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PHENCOMP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PHENCVTERM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PHENDESC_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PHENOTYPE_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PHENSTATEMENT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PROJECT_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PROTOCOLPARAM_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_PROTOCOL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_QUANPROP_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_QUANREL_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_QUANTIFICATION_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_STUACTO_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_STUDDEIPR_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_STUDYDESIGN_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_STUDYFACTOR_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_STUDY_ASSAY_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_STUDY_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_SYNONYM__TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_TABLEINFO_TRG DISABLE;

ALTER TRIGGER AUDIT_CHADO_TREATMENT_TRG DISABLE;

ALTER TRIGGER AUD_ACQUISITION DISABLE;

ALTER TRIGGER AUD_ACQUISITIONPROP DISABLE;

ALTER TRIGGER AUD_ACQUISITION_RELATIONSHIP DISABLE;

ALTER TRIGGER AUD_ANALYSIS DISABLE;

ALTER TRIGGER AUD_ANALYSISFEATURE DISABLE;

ALTER TRIGGER AUD_ANALYSISPROP DISABLE;

ALTER TRIGGER AUD_ARRAYDESIGN DISABLE;

ALTER TRIGGER AUD_ARRAYDESIGNPROP DISABLE;

ALTER TRIGGER AUD_ASSAY DISABLE;

ALTER TRIGGER AUD_ASSAYPROP DISABLE;

ALTER TRIGGER AUD_ASSAY_BIOMATERIAL DISABLE;

ALTER TRIGGER AUD_ASSAY_PROJECT DISABLE;

ALTER TRIGGER AUD_AUTHOR DISABLE;

ALTER TRIGGER AUD_BIOMATERIAL DISABLE;

ALTER TRIGGER AUD_BIOMATERIALPROP DISABLE;

ALTER TRIGGER AUD_BIOMATERIAL_RELATIONSHIP DISABLE;

ALTER TRIGGER AUD_BIOMATERIAL_TREATMENT DISABLE;

ALTER TRIGGER AUD_CHANNEL DISABLE;

ALTER TRIGGER AUD_CONTACT DISABLE;

ALTER TRIGGER AUD_CONTROL DISABLE;

ALTER TRIGGER AUD_CV DISABLE;

ALTER TRIGGER AUD_CVTERM DISABLE;

ALTER TRIGGER AUD_CVTERMPATH DISABLE;

ALTER TRIGGER AUD_CVTERMPROP DISABLE;

ALTER TRIGGER AUD_CVTERMSYNONYM DISABLE;

ALTER TRIGGER AUD_CVTERM_DBXREF DISABLE;

ALTER TRIGGER AUD_CVTERM_RELATIONSHIP DISABLE;

ALTER TRIGGER AUD_DB DISABLE;

ALTER TRIGGER AUD_DBXREF DISABLE;

ALTER TRIGGER AUD_DBXREFPROP DISABLE;

ALTER TRIGGER AUD_EIMAGE DISABLE;

ALTER TRIGGER AUD_ELEMENT DISABLE;

ALTER TRIGGER AUD_ELEMENTRESULT DISABLE;

ALTER TRIGGER AUD_ELEMENTRESULT_RELATIONSHIP DISABLE;

ALTER TRIGGER AUD_ENVIRONMENT DISABLE;

ALTER TRIGGER AUD_ENVIRONMENT_CVTERM DISABLE;

ALTER TRIGGER AUD_EXPRESSION DISABLE;

ALTER TRIGGER AUD_EXPRESSION_CVTERM DISABLE;

ALTER TRIGGER AUD_EXPRESSION_IMAGE DISABLE;

ALTER TRIGGER AUD_EXPRESSION_PUB DISABLE;

ALTER TRIGGER AUD_FEATURE DISABLE;

ALTER TRIGGER AUD_FEATURELOC DISABLE;

ALTER TRIGGER AUD_FEATUREMAP DISABLE;

ALTER TRIGGER AUD_FEATUREMAP_PUB DISABLE;

ALTER TRIGGER AUD_FEATUREPOS DISABLE;

ALTER TRIGGER AUD_FEATUREPROP DISABLE;

ALTER TRIGGER AUD_FEATUREPROP_PUB DISABLE;

ALTER TRIGGER AUD_FEATURERANGE DISABLE;

ALTER TRIGGER AUD_FEATURE_CVTERM DISABLE;

ALTER TRIGGER AUD_FEATURE_CVTERMPROP DISABLE;

ALTER TRIGGER AUD_FEATURE_CVTERM_DBXREF DISABLE;

ALTER TRIGGER AUD_FEATURE_CVTERM_PUB DISABLE;

ALTER TRIGGER AUD_FEATURE_DBXREF DISABLE;

ALTER TRIGGER AUD_FEATURE_EXPRESSION DISABLE;

ALTER TRIGGER AUD_FEATURE_GENOTYPE DISABLE;

ALTER TRIGGER AUD_FEATURE_PHENOTYPE DISABLE;

ALTER TRIGGER AUD_FEATURE_RELATIONSHIP DISABLE;

ALTER TRIGGER AUD_FEATURE_RELATIONSHIPPROP DISABLE;

ALTER TRIGGER AUD_FEATURE_SYNONYM DISABLE;

ALTER TRIGGER AUD_GENOTYPE DISABLE;

ALTER TRIGGER AUD_MAGEDOCUMENTATION DISABLE;

ALTER TRIGGER AUD_MAGEML DISABLE;

ALTER TRIGGER AUD_ORGANISM DISABLE;

ALTER TRIGGER AUD_ORGANISMPROP DISABLE;

ALTER TRIGGER AUD_ORGANISM_DBXREF DISABLE;

ALTER TRIGGER AUD_PHENDESC DISABLE;

ALTER TRIGGER AUD_PHENOTYPE DISABLE;

ALTER TRIGGER AUD_PHENOTYPE_COMPARISON DISABLE;

ALTER TRIGGER AUD_PHENOTYPE_CVTERM DISABLE;

ALTER TRIGGER AUD_PHENSTATEMENT DISABLE;

ALTER TRIGGER AUD_PROJECT DISABLE;

ALTER TRIGGER AUD_PROTOCOL DISABLE;

ALTER TRIGGER AUD_PROTOCOLPARAM DISABLE;

ALTER TRIGGER AUD_QUANTIFICATION DISABLE;

ALTER TRIGGER AUD_QUANTIFICATIONPROP DISABLE;

ALTER TRIGGER AUD_QUANTIFICATION_REL DISABLE;

ALTER TRIGGER AUD_STUDY DISABLE;

ALTER TRIGGER AUD_STUDYDESIGN DISABLE;

ALTER TRIGGER AUD_STUDYDESIGNPROP DISABLE;

ALTER TRIGGER AUD_STUDYFACTOR DISABLE;

ALTER TRIGGER AUD_STUDYFACTORVALUE DISABLE;

ALTER TRIGGER AUD_STUDY_ASSAY DISABLE;

ALTER TRIGGER AUD_SYNONYM_ DISABLE;

ALTER TRIGGER AUD_TABLEINFO DISABLE;

ALTER TRIGGER AUD_TREATMENT DISABLE;
